### ISSUE TITLE
Multiple frames

### ISSUE THREAD

**Issue by jondeandres** [iliabylich/binding_dumper#2]
Hey,

this work is awesome, really cool!

Do you find viable get the binding in last X frames? 

I think this cannot be done without C extensions and not production ready. But maybe Ruby has improved on this. Any idea?

**Comment by iliabylich** [comment]
Hi @jondeandres 

I'm not sure that I understand you correctly. What do you mean by saying 'frame' ? Could you probably provide some code example of what do you need?

**Comment by jondeandres** [comment]
Oh sorry @iliabylich, when I say frame I'm refering to every context in the call trace, and not only in the current context.

**Comment by ghost** [comment]
Alright, then you might want to use the gem [binding_of_caller](https://github.com/banister/binding_of_caller). Could you check it?
