### ISSUE TITLE
What difference with this gem and following code?

### ISSUE THREAD

**Issue by zw963** [iliabylich/binding_dumper#3]
Hi, I am play with following code, it work quite good with my rails project.

```rb
# only for MRI 2.0+
def Rescue(klass=nil, message=nil)
  TracePoint.trace(:raise) do |tp|
    exit if self.Pry_is_start

    unless klass.nil?
      next if tp.raised_exception.class != klass
    end

    unless message.nil?
      next if tp.raised_exception.message != message
    end

    require 'pry'
    require 'binding_of_caller'
    self.Pry_is_start = true

    binding.of_caller(3).pry
  end
  yield
end
```

Following is usage:

```rb
Rescue NoMethodError do
   # some code which maybe throw `NoMethodError` exception
    ....
end
```

When that Exception is raise, Rescue will catch it, and load pry on that context.

I want to know, what is the advantage this gem compare to this?

**Comment by iliabylich** [comment]
@zw963 I'm not sure that you get the idea of the gem. It allows to "convert" a binding to some serializable data that can be stored and converted back to binding later.
Your code snippet runs `pry` on every rescued exception. Are you that you submitted it to correct repo?

**Comment by zw963** [comment]
I remember this gem after one or two years see this gem, but i still could not found a good use case
for this, But, I keep think this gem is interest ...

**Comment by zw963** [comment]
Hi, @iliabylich , maybe i ask wrong problem, but, do you think (like me), if this gem worked together
with `TracePoint.trace(:raise) { .... }`, to dump a binding data into database when some unexpect
exception is raise, that is a good idea to debug? 


anyway, no one directly use pry or irb in production live project, but collection info for later local
analysis is a good idea.
